### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by laurentpetit** [verma/clj-slackbot#3]
Hello, 

I configured clj-slackbot on a server, and create the relevant slack commands and incoming web hooks.

I have started my slackbot as such:

`POST_URL=https://hooks.slack.com/services/.... COMMAND_TOKEN=xxxx java -jar ./.clj-slackbot.jar`

When I issue command from slack, I see activity and the following error in the bot logs:

```
java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
    at java.security.AccessController.checkPermission(AccessController.java:559)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at java.net.ProxySelector.getDefault(ProxySelector.java:94)
    at org.apache.http.impl.conn.ProxySelectorRoutePlanner.determineProxy(ProxySelectorRoutePlanner.java:174)
    at org.apache.http.impl.conn.ProxySelectorRoutePlanner.determineRoute(ProxySelectorRoutePlanner.java:138)
    at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:762)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:381)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at clj_http.core$request.invoke(core.clj:289)
    at clojure.lang.Var.invoke(Var.java:379)
    at clj_http.client$wrap_request_timing$fn__6321.invoke(client.clj:751)
    at clj_http.headers$wrap_header_map$fn__5187.invoke(headers.clj:138)
    at clj_http.client$wrap_query_params$fn__6235.invoke(client.clj:577)
    at clj_http.client$wrap_basic_auth$fn__6242.invoke(client.clj:594)
    at clj_http.client$wrap_oauth$fn__6246.invoke(client.clj:604)
    at clj_http.client$wrap_user_info$fn__6251.invoke(client.clj:617)
    at clj_http.client$wrap_url$fn__6307.invoke(client.clj:717)
    at clj_http.client$wrap_redirects$fn__6073.invoke(client.clj:212)
    at clj_http.client$wrap_decompression$fn__6095.invoke(client.clj:284)
    at clj_http.client$wrap_input_coercion$fn__6179.invoke(client.clj:423)
    at clj_http.client$wrap_additional_header_parsing$fn__6200.invoke(client.clj:494)
    at clj_http.client$wrap_output_coercion$fn__6170.invoke(client.clj:398)
    at clj_http.client$wrap_exceptions$fn__6053.invoke(client.clj:164)
    at clj_http.client$wrap_accept$fn__6210.invoke(client.clj:522)
    at clj_http.client$wrap_accept_encoding$fn__6216.invoke(client.clj:536)
    at clj_http.client$wrap_content_type$fn__6205.invoke(client.clj:511)
    at clj_http.client$wrap_form_params$fn__6286.invoke(client.clj:682)
    at clj_http.client$wrap_nested_params$fn__6303.invoke(client.clj:706)
    at clj_http.client$wrap_method$fn__6256.invoke(client.clj:624)
    at clj_http.cookies$wrap_cookies$fn__3874.invoke(cookies.clj:122)
    at clj_http.links$wrap_links$fn__5367.invoke(links.clj:50)
    at clj_http.client$wrap_unknown_host$fn__6311.invoke(client.clj:726)
    at clj_http.client$post.doInvoke(client.clj:841)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at clj_slackbot.core.handler$post_to_slack.invoke(handler.clj:30)
    at clj_slackbot.core.handler$eval_and_post.invoke(handler.clj:71)
```

Any idea what could have been done wrong?

**Comment by verma** [comment]
Hmm, could you tell me a little bit more about where you're running it? Seems like may be a system policy is causing this to happen?

**Comment by laurentpetit** [comment]
On a classic Ubuntu server 14.04 directly connected to the Internet.
I'll try to activate more traces. If you have any tips on how to do so at
your hand ...

Le lundi 21 septembre 2015, Uday Verma notifications@github.com a écrit :

> Hmm, could you tell me a little bit more about where you're running it?
> Seems like may be a system policy is causing this to happen?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/verma/clj-slackbot/issues/3#issuecomment-142074348.

## 

Laurent Petit

**Comment by verma** [comment]
Did you make any progress on this front?  I see that this [1] fork as done a bunch of work on top of what's here, may be you'd have better luck trying it out?  I see some stuff dealing with java's security policies.

[1] https://github.com/esdee/clj-slackbot/commits/master

**Comment by laurentpetit** [comment]
Hello, 
in the mean time, I've rolled up my sleeves and commited to write my own integration layer. It was the opportunity for me to learn more about websockets. Had a fun week-end, and my bot is already running using the RTM API :-)

So sorry, but I haven't had the opportunity to dig deeper, and I don't think i will have the time to do so.

**Comment by verma** [comment]
Sounds great, I haven't looked into RTM API myself, but looks like a fun project.

**Comment by laurentpetit** [comment]
Yeah. I may consider releasing what I've done at some point in time. It's really not a lot of code or dependencies : a clj wrapper over jetty websockets, clj-http, and cheshire for json interop.
